### PR TITLE
update abi file

### PR DESCRIPTION
**Pull request by boundless-forest**

### CODE REVIEW

**Comment by kaikai1024** [comment]
no need to add *Creator abi file. because it can only be called by *Management (contract)

**Comment by boundless-forest** [comment]
> no need to add *Creator abi file. because it can only be called by *Management (contract)

I need these abi files when creating genesis using  [ethabi constructor](https://docs.rs/ethabi/8.0.0/ethabi/struct.Contract.html#method.load). 

`PriceManager.abi` and `VersionManager.abi` also need updated, i will push later.

**Comment by kaikai1024** [comment]
ok

**Comment by boundless-forest** [comment]
@kaikai1024 Please review it again :smiley:

**Review by kaikai1024 — APPROVED** [review]

**Pull request merged**
